name: eh_redux
description: EH Redux
publish_to: 'none'
version: 0.5.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  http: ^0.12.1
  html: ^0.14.0+3
  cached_network_image: ^2.2.0+1
  built_collection: ^4.3.2
  provider: ^4.1.2
  meta: ^1.1.8
  mobx: ^1.2.1
  flutter_mobx: ^1.1.0
  built_value: ^7.1.0
  share: ">=0.6.4+3 <2.0.0"
  photo_view: ^0.9.2
  shared_preferences: ">=0.5.7+3 <2.0.0"
  preload_page_view: ^0.1.4
  collection: ^1.14.12
  flutter_secure_storage: ^3.3.3
  webview_flutter: ^0.3.22+1
  package_info: ">=0.4.1 <2.0.0"
  url_launcher: ^5.4.10
  filesize: ^1.0.4
  intl: ^0.16.1
  firebase_core: ^0.4.5
  firebase_analytics: ^5.0.15
  firebase_crashlytics: ^0.1.3+3
  flutter_markdown: ^0.4.2
  freezed_annotation: ^0.11.0
  json_annotation: ^3.0.1
  moor: 3.1.0
  moor_ffi: ^0.5.0
  path: ^1.6.4
  path_provider: ^1.6.11
  flutter_typeahead: ^1.8.3
  device_info: ">=0.4.2+4 <2.0.0"
  workmanager: ^0.2.3
  flutter_local_notifications: ^1.4.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.6.5
  mobx_codegen: ^1.1.0
  built_value_generator: ^7.1.0
  lint: ^1.0.0
  mockito: ^4.1.1
  matcher: ^0.12.6
  freezed: ^0.11.2
  json_serializable: ^3.3.0
  json_serializable_immutable_collections: ^0.3.0
  moor_generator: 3.1.0

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
